FROM ubuntu
# ...
ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update && \
    apt-get -y install gcc mono-mcs && \
    rm -rf /var/lib/apt/lists/*

FROM golang:1.19.1

RUN go mod download
RUN go build .
EXPOSE 8080

CMD [ "/railway" ]